tester = input('Digite o que quiser: ')
print(tester, type(tester))
print('O valor digitado é alphanumérico?', tester.isalnum())
print('Númerico?', tester.isnumeric())
print('O valor digitado é alphabetico?', tester.isalpha())
print('O valor digitado é decimal?', tester.isdecimal())
print('O valor digitado é um digito?', tester.isdigit())
print('O valor digitado é lower?', tester.islower())
print('Printable?', tester.isprintable())
print('Espaços?', tester.isspace())
print('Captalizado?', tester.istitle())
print('Caixa alta?', tester.isupper())
print('São minusculas?', tester.islower())
