frase = input('Frase bunita: ').strip().lower()
print(frase)
print(f'A letra <a> aparece {frase.count("a")} vezes')
print(f'A primeira vez na posição {frase.find("a")+1}')
print(f'E a ultima na posição {frase.rfind("a")+1}')
